# Generated by Django 2.2.6 on 2019-11-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tnkb_colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, default='', max_length=100)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('variety', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tnkb_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tnkb_colors.TnkbColor')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
